Update jenkinsfile2 with env variable for mvn

diff --git a/reusable-pipelines/refactoring-pipeline/jenkinsfile2 b/reusable-pipelines/refactoring-pipeline/jenkinsfile2
--- a/reusable-pipelines/refactoring-pipeline/jenkinsfile2
+++ b/reusable-pipelines/refactoring-pipeline/jenkinsfile2
@@ -1,16 +1,20 @@
 pipeline {
     agent any
+    
     environment {
-        VERSION = '2.1.0'
+        VERSION = '0.1.0'
         RELEASE_VERSION = 'R.2'
+        M2_HOME = '/opt/apache-maven-3.6.3'
+        PATH = "$M2_HOME/bin:$PATH"
     }
+
     stages {
         stage('Audit tools') {
             steps {
                 sh '''
-                  git version
-                  java -version
-                  mvn -version
+                    git version
+                    java -version
+                    mvn -version
                 '''
             }
         }
@@ -30,14 +34,21 @@ pipeline {
             steps {
                 echo "Building version: ${VERSION} with suffix: ${RELEASE_VERSION}"
                 echo 'Mention your Application Build Code here!!!'
-                dir('./java-tomcat-sample') {
-                        sh '''
-                            mvn versions:set -DnewVersion="${VERSION}"-SNAPSHOT
-                            mvn versions:update-child-modules
-                            mvn clean package
-                        '''
-                    }
+                sh '''
+                    mvn versions:set -DnewVersion="${VERSION}"-SNAPSHOT
+                    mvn versions:update-child-modules
+                    mvn clean package
+                '''
             }
+        }
+    }
+
+    post {
+        success {
+            echo 'Pipeline succeeded!'
+        }
+        failure {
+            echo 'Pipeline failed!'
         }
     }
 }
